const DRIVER_DATA = [
  {
    name: "Max Verstappen",
    number: 33,
    abbreviation: "VER",
    points: 25,
    wins: 1,
    team: "Red Bull",
  },
  {
    name: "Lewis Hamilton",
    number: 44,
    abbreviation: "HAM",
    points: 28,
    wins: 0,
    team: "Mercedes",
  },
  {
    name: "George Russell",
    number: 63,
    abbreviation: "RUS",
    points: 37,
    wins: 0,
    team: "Mercedes",
  },
  {
    name: "Sergio Perez",
    number: 11,
    abbreviation: "PER",
    points: 30,
    wins: 0,
    team: "Red Bull",
  },
  {
    name: "Lando Norris",
    number: 4,
    abbreviation: "NOR",
    points: 16,
    wins: 0,
    team: "McLaren",
  },
  {
    name: "Charles Leclerc",
    number: 16,
    abbreviation: "LEC",
    points: 71,
    wins: 2,
    team: "Ferrari",
  },
  {
    name: "Carlos Sainz",
    number: 55,
    abbreviation: "SAI",
    points: 33,
    wins: 0,
    team: "Ferrari",
  },
  {
    name: "Daniel Ricciardo",
    number: 3,
    abbreviation: "RIC",
    points: 8,
    wins: 0,
    team: "McLaren",
  },
  {
    name: "Pierre Gasly",
    number: 10,
    abbreviation: "GAS",
    points: 6,
    wins: 0,
    team: "AlphaTauri",
  },
  {
    name: "Fernando Alonso",
    number: 14,
    abbreviation: "ALO",
    points: 2,
    wins: 0,
    team: "Alpine",
  },
  {
    name: "Esteban Ocon",
    number: 31,
    abbreviation: "OCO",
    points: 20,
    wins: 0,
    team: "Alpine",
  },
  {
    name: "Sebastian Vettel",
    number: 5,
    abbreviation: "VET",
    points: 0,
    wins: 0,
    team: "Aston Martin",
  },
  {
    name: "Lance Stroll",
    number: 18,
    abbreviation: "STR",
    points: 0,
    wins: 0,
    team: "Aston Martin",
  },
  {
    name: "Yuki Tsunoda",
    number: 22,
    abbreviation: "TSU",
    points: 4,
    wins: 0,
    team: "AlphaTauri",
  },
  {
    name: "Valtteri Bottas",
    number: 77,
    abbreviation: "BOT",
    points: 12,
    wins: 0,
    team: "Alfa Romeo",
  },
  {
    name: "Guanyu Zhou",
    number: 37,
    abbreviation: "ZHO",
    points: 1,
    wins: 0,
    team: "Alfa Romeo",
  },
  {
    name: "Nicholas Latifi",
    number: 6,
    abbreviation: "LAT",
    points: 0,
    wins: 0,
    team: "Williams",
  },
  {
    name: "Alex Albon",
    number: 23,
    abbreviation: "ALB",
    points: 1,
    wins: 0,
    team: "Williams",
  },
  {
    name: "Mick Schumacher",
    number: 47,
    abbreviation: "MSC",
    points: 0,
    wins: 0,
    team: "Haas",
  },
  {
    name: "Kevin Magnussen",
    number: 20,
    abbreviation: "MAG",
    points: 12,
    wins: 0,
    team: "Haas",
  },
];

export default DRIVER_DATA;
