const DRIVER_DATA = [
  {
    name: "Max Verstappen",
    number: 33,
    abbreviation: "VER",
    points: 369.5,
    wins: 9,
    team: "Red Bull",
  },
  {
    name: "Lewis Hamilton",
    number: 44,
    abbreviation: "HAM",
    points: 369.5,
    wins: 8,
    team: "Mercedes",
  },
  {
    name: "Valtteri Bottas",
    number: 77,
    abbreviation: "BOT",
    points: 218,
    wins: 1,
    team: "Mercedes",
  },
  {
    name: "Sergio Perez",
    number: 11,
    abbreviation: "PER",
    points: 190,
    wins: 1,
    team: "Red Bull",
  },
  {
    name: "Lando Norris",
    number: 4,
    abbreviation: "NOR",
    points: 154,
    wins: 0,
    team: "McLaren",
  },
  {
    name: "Charles Leclerc",
    number: 16,
    abbreviation: "LEC",
    points: 158,
    wins: 0,
    team: "Ferrari",
  },
  {
    name: "Carlos Sainz",
    number: 55,
    abbreviation: "SAI",
    points: 149.5,
    wins: 0,
    team: "Ferrari",
  },
  {
    name: "Daniel Ricciardo",
    number: 3,
    abbreviation: "RIC",
    points: 115,
    wins: 1,
    team: "McLaren",
  },
  {
    name: "Pierre Gasly",
    number: 10,
    abbreviation: "GAS",
    points: 100,
    wins: 0,
    team: "AlphaTauri",
  },
  {
    name: "Fernando Alonso",
    number: 14,
    abbreviation: "ALO",
    points: 77,
    wins: 0,
    team: "Alpine",
  },
  {
    name: "Esteban Ocon",
    number: 31,
    abbreviation: "OCO",
    points: 72,
    wins: 1,
    team: "Alpine",
  },
  {
    name: "Sebastian Vettel",
    number: 5,
    abbreviation: "VET",
    points: 43,
    wins: 0,
    team: "Aston Martin",
  },
  {
    name: "Lance Stroll",
    number: 18,
    abbreviation: "STR",
    points: 34,
    wins: 0,
    team: "Aston Martin",
  },
  {
    name: "Yuki Tsunoda",
    number: 22,
    abbreviation: "TSU",
    points: 20,
    wins: 0,
    team: "AlphaTauri",
  },
  {
    name: "George Russell",
    number: 63,
    abbreviation: "RUS",
    points: 16,
    wins: 0,
    team: "Williams",
  },
  {
    name: "Kimi Räikkönen",
    number: 7,
    abbreviation: "RAI",
    points: 10,
    wins: 0,
    team: "Alfa Romeo",
  },
  {
    name: "Nicholas Latifi",
    number: 6,
    abbreviation: "LAT",
    points: 7,
    wins: 0,
    team: "Williams",
  },
  {
    name: "Antonio Giovinazzi",
    number: 99,
    abbreviation: "GIO",
    points: 3,
    wins: 0,
    team: "Alfa Romeo",
  },
  {
    name: "Mick Schumacher",
    number: 47,
    abbreviation: "MSC",
    points: 0,
    wins: 0,
    team: "Haas",
  },
  {
    name: "Nikita Mazepin",
    number: 9,
    abbreviation: "MAZ",
    points: 0,
    wins: 0,
    team: "Haas",
  },
];

export default DRIVER_DATA;
